# listen on... can be an IP or an interface
internal.protocol: ipv4 ipv6
internal: end0 port = 1080
# send out through... can be an IP or an interface
external.protocol: ipv4 ipv6
external: end0
# for user auth run as this user
user.privileged:   root
# otherwise run as this user
user.unprivileged: nobody
# auth with user login, passwd
# socksmethod:       username
# no authentication
clientmethod: none
socksmethod: none
# log to stdout
logoutput:         /dev/stdout
#debug: 1
# allow everyone from everywhere so long as they auth, log errors
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error # connect disconnect iooperation
}
# allow IPv6
client pass {
    from: ::/0 to: ::/0
    log: error # connect disconnect iooperation
}
# allow everyone from everywhere so long as they auth, log errors
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: bind connect udpassociate
    log: error # connect disconnect iooperation
}
# same for IPv6
socks pass {
    from: ::/0 to: ::/0
    command: bind connect udpassociate
    log: error # connect disconnect iooperation
}
# generic pass statement for incoming connections/packets
# because something about no support for auth with bindreply udpreply ?
socks pass {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        command: bindreply udpreply
        log: error # connect disconnect iooperation
}
socks pass {
	from: ::/0 to: ::/0
        command: bindreply udpreply
        log: error # connect disconnect iooperation
}
socks block {
	from: 0/0 to: 0/0
	log: error # connect iooperation
}
